# Generated by Django 4.0.2 on 2022-02-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
